'use client'

// src/hooks/usePromptManager.ts
import { useState, useEffect } from 'react';
import { buildAIPrompt, BaseGenerationParams, ImageDetails } from '@/lib/prompt-builder';

interface UsePromptManagerProps {
  initialPrompt?: string;
  generationType: 'image' | 'video';
  generationParams: BaseGenerationParams;
  imageDetails?: ImageDetails; // Optional, mainly for image type
}

export function usePromptManager({
  initialPrompt = '',
  generationType,
  generationParams,
  imageDetails,
}: UsePromptManagerProps) {
  const [currentPrompt, setCurrentPrompt] = useState<string>(initialPrompt);
  const [isPromptManuallyEdited, setIsPromptManuallyEdited] = useState<boolean>(false);

  // eslint-disable-next-line react-hooks/exhaustive-deps -- React Compiler auto-memoizes this function
  function generatePromptFromParams() {
    return buildAIPrompt({
      type: generationType,
      params: generationParams,
      imageDetails: imageDetails,
    });
  }

  useEffect(() => {
    if (!isPromptManuallyEdited) {
      setCurrentPrompt(generatePromptFromParams());
    }
  }, [isPromptManuallyEdited, generatePromptFromParams]);

  function handlePromptChange(newPrompt: string) {
    setCurrentPrompt(newPrompt);
    setIsPromptManuallyEdited(true);
  }

  function resetPromptToAuto() {
    setIsPromptManuallyEdited(false);
    // The useEffect above will trigger a regeneration of the prompt
    // and update currentPrompt if isPromptManuallyEdited was true.
    // If it was already false, explicitly set it to ensure re-render if params changed meanwhile.
    setCurrentPrompt(generatePromptFromParams());
  }

  // This checks if the current manual prompt is out of sync with what would be auto-generated.
  const isManualPromptOutOfSync: boolean = (() => {
    if (!isPromptManuallyEdited) return false;
    return currentPrompt !== generatePromptFromParams();
  })();

  return {
    currentPrompt,
    isPromptManuallyEdited,
    handlePromptChange,
    resetPromptToAuto,
    isManualPromptOutOfSync, // Expose this for UI warnings
    // rawAutoGeneratedPrompt: generatePromptFromParams() // Could be exposed for comparison if needed
  };
}
